version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "chore"
    allow:
      - dependency-type: "direct"
    labels:
      - 'dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - 'dependencies'

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - 'dependencies'
