name: Check code health

on:
  push:
    branches: [ master, main ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Run lint
        run: make lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Run tests
        run: make test-reports

      - name: Upload tests report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: coverage/**/*

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Build the application
        run: make build
