name: Check code health

on:
  push:
    branches: [ master, main ]

jobs:
  Scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan the repository to find hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Run lint
        run: make lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Run tests
        run: make test-reports

      - name: Upload tests report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: coverage/**/*

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup project
        run: make setup || make setup || make setup

      - name: Build the application
        run: make build
